# Generated by Django 5.1.6 on 2025-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('status', models.CharField(default='found', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('status', models.CharField(default='lost', max_length=20)),
            ],
        ),
    ]
